### ISSUE TITLE
way to improving GPS Signals on bgeige nano

### ISSUE THREAD

**Issue by Lugulbanda** [Safecast/bGeigieNanoKit#43]
hi short question, is there a way to improve that sattelite location for the bgeige nano, 
i noticed that i sometimes have lots of measuringpoinst getting flagged out, some times not a single one sometimes half or more of the hole measurment walk/drive, i think most is because of blockign throught strucktures, like tunnels Roofs were the car is staying under, while getting food or fuel, so my questions

is there a way to strengthen the signalantenna?
on wich GPS is the Nano working?
i know there are new chips out wich dont adjust only on one system only, and use glonas gallileo or the chinese gps...
i know special the normal GPS is damped if, some Warstrickes are done in certain regions, 
if there is a softwareupdate, for the nano were can i find it, if there is a improved singal calculation ?

**Comment by seanbonner** [comment]
There is a little connector for an antenna on the GPS module if you feel the need to attach an antenna, but we use that Ultimate GPS breakout board and chip because it’s head and shoulders better than everything else we tried. There’s no new firmware to make it better, any GPS will stop working when you are inside a structure because it’s recalculating your position all the time and if it can’t see any satellites then it will not connect to any to get a reading. If you are having problems with your GPS getting readings when you are outside walking then you might just need to reset it, take the SD card out, turn the bGeigie on for 1 minute and then turn off and put SD card back in, that’ll force a hard reboot.

-s

Sean Bonner
Co-Founder, Director of Global Operations
Safecast.org | pgp key

On January 4, 2018 at 1:28:15 AM, Lugulbanda (notifications@github.com) wrote:

hi short question, is there a way to improve that sattelite location for the bgeige nano,
i noticed that i sometimes have lots of measuringpoinst getting flagged out, some times not a single one sometimes half or more of the hole measurment walk/drive, i think most is because of blockign throught strucktures, like tunnels Roofs were the car is staying under, while getting food or fuel, so my questions

is there a way to strengthen the signalantenna?
on wich GPS is the Nano working?
i know there are new chips out wich dont adjust only on one system only, and use glonas gallileo or the chinese gps...
i know special the normal GPS is damped if, some Warstrickes are done in certain regions,
if there is a softwareupdate, for the nano were can i find it, if there is a improved singal calculation ?

**Comment by Lugulbanda** [comment]
thx for the info for reboot, problem is u notice it first if ur at home and look what u measured so far, and then its to late, when this xxx points are flagged out because of no GPS, and there is a lot more GPS over us then only one system...

**Comment by seanbonner** [comment]
We are not using “one GPS system” this is an Ultimate GPS chip which can get a signal from any GPS satellite so it works very well everywhere in the world. The display will tell you if you don’t have GPS lock, but again if you are outside then it will work perfectly, inside no GPS will work. If it’s outside and not working then you might have a different problem going on with the soldering or something, but it’s not lack of GPS reception.

On January 4, 2018 at 4:15:47 PM, Lugulbanda (notifications@github.com) wrote:

thx for the info for reboot, problem is u notice it first if ur at home and look what u measured so far, and then its to late, when this xxx points are flagged out because of no GPS, and there is a lot more GPS over us then only one system...

**Comment by thinrope** [comment]
@Lugulbanda, yes there exists other non-GPS navigational systems (GNSSes), most useful being GLONASS, but the large field deployment and reliability tests of this particular unit has proven good enough for most purposes. When we test units inside buildings (office, home), we connect additional antenna to the uFL connector with a long cable and set the antenna near a window.
There is always an ongoing "navigational race" and may be one day in the future we can update the design with a navigational module that supports other GNSSes like GLONASS, Galileo, BeiDou, etc. Given the openness of the project, feel free to experiment yourself!

**Comment by Lugulbanda** [comment]
thx :)
